=== vladvicus/TATJAVA01_2017_Task05_Uladzislau_Palupan/data/menu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.epam.tc.com/items"
           xmlns="http://www.epam.tc.com/items"
           elementFormDefault="qualified">


    <xs:element name="items" type="ItemType"/>

    <xs:complexType name="ItemType">
        <xs:complexContent>
            <xs:restriction base="xs:anyType">
                <xs:sequence>
                    <xs:element name="cold_dishes" type="Dishes"/>
                    <xs:element name="hot_dishes" type="Dishes"/>
                    <xs:element name="breakfasts" type="Dishes"/>
                </xs:sequence>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType>


    <xs:complexType name="Dishes">
        <xs:sequence>
            <xs:element name="dish" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:complexContent>
                        <xs:restriction base="xs:anyType">
                            <xs:sequence>
                                <xs:element name="foto">
                                    <xs:complexType>
                                        <xs:attribute name="src" type="xs:anyURI"/>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="name" type="xs:string"/>
                                <xs:element name="description" minOccurs="0" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:complexContent>
                                            <xs:extension base="xs:anyType">
                                                <xs:attribute name="price" default="">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:pattern value="\d{1,3}руб|\s*"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>

                                            </xs:extension>
                                        </xs:complexContent>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="portion">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:pattern value="(\d{1,2}шт.)|[\d//]+"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:element>

                            </xs:sequence>
                            <xs:attribute name="id" type="xs:ID" use="required"/>
                        </xs:restriction>
                    </xs:complexContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>


</xs:schema>

=== vladvicus/TATJAVA01_2017_Task05_Uladzislau_Palupan/data/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<items xmlns="http://www.epam.tc.com/items"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.epam.tc.com/items menu.xsd">

    <cold_dishes>
        <dish id="c1">
            <foto src="http://photo0_1.jpg"/>
            <name>Ассорти рыбное</name>
            <description price="10руб">Слабосоленая форель,семга</description>
            <portion>100/20/15</portion>
        </dish>
        <dish id="c2">
            <foto src="http://photo0_2.jpg"/>
            <name>Тарталетки с красной икрой</name>
            <description price="10руб">Тарталетки с красной икрой</description>
            <portion>60/50</portion>
        </dish>
    </cold_dishes>
    <hot_dishes>
        <dish id="h1">
            <foto src="http://photo1_1.jpg"/>
            <name>Лобио с шампиньонами</name>
            <description price="8руб">Фасоль с шампиньонами и грецким орехом</description>
            <portion>150/5</portion>
        </dish>
        <dish id="h2">
            <foto src="http://photo1_2.jpg"/>
            <name>Жульен</name>
            <description price="145руб">Жульен с курицей</description>
            <description price="155руб">Жульен с грибами</description>
            <portion>120/1</portion>
        </dish>
    </hot_dishes>
    <breakfasts>
        <dish id="a1">
            <foto src="http://photo2_1.jpg"/>
            <name>Глазунья</name>
            <description price="">2 яйца с ветчиной</description>
            <description price="5руб">2 яйца с сыром</description>
            <description price="">2 яйца с помидором</description>
            <portion>150</portion>
        </dish>
        <dish id="a2">
            <foto src="http://photo2_2.jpg"/>
            <name>Омлет</name>
            <description price="10руб"></description>
            <portion>100</portion>
        </dish>
    </breakfasts>
</items>
